In [3]:
import numpy as np
 
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 


In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

array([1, 2, 3])

In [6]:
np.sum(arr, axis=1) #Sum of all row's number

array([ 6, 15, 24])

In [7]:
np.sum(arr, axis=0) #Sum of all colom's number

array([12, 15, 18])

In [8]:
arr[0][1]

np.int64(2)

In [9]:
arr[0, 1]

np.int64(2)

In [10]:
arr[0:2 , 1:3] # 0 se 1 index wala row and 1 se 2 index wala colom, show hoga overlapping wala area

array([[2, 3],
       [5, 6]])

In [13]:
arr3D = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
                
    [[7, 8, 9],
    [10, 11, 12]]
])

In [14]:
print(arr3D[:, 0, :]) 

[[1 2 3]
 [7 8 9]]


In [16]:
(arr3D[:, 0, :]) = 0 # Changing data along an axis

In [17]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])