In [1]:
import numpy as np


In [4]:
arr = np.array([1,3,4])

In [5]:
arr

array([1, 3, 4])

In [7]:
arr2 = np.array([[1,3,5] , [2,7,9]])

In [8]:
arr2

array([[1, 3, 5],
       [2, 7, 9]])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.full((4,5) , 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(1,100 , 9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [15]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [20]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [21]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
myarr.shape

(4, 3)

In [23]:
myarr.size

12

In [24]:
myarr.ndim

2

In [25]:
myarr.dtype

dtype('int64')

In [38]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = 'float32')

In [39]:
myarr.astype('float64')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [40]:
n = myarr.astype('float64')

In [41]:
n.dtype

dtype('float64')

In [42]:
myarr.dtype

dtype('float32')

In [43]:
myarr.shape

(4, 3)

In [47]:
reshaped = myarr.reshape((3,4))

In [48]:
reshaped

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [49]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)