In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]

np.int64(1)

In [8]:
flat[3]

np.int64(4)

In [10]:
flat[3: 6]

array([4, 5, 6])

In [11]:
flat[:5] #Same as flat[0:5]

array([1, 2, 3, 4, 5])

In [12]:
flat[3:] #Same as flat[3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
b = flat[3:7]

In [14]:
b

array([4, 5, 6, 7])

In [15]:
b[0]

np.int64(4)

In [16]:
b[0] = 444

In [17]:
b

array([444,   5,   6,   7])

In [18]:
flat

array([  1,   2,   3, 444,   5,   6,   7,   8,   9,  10,  11,  12])

In [22]:
arr = np.array([1,54,23,53,2,3,34,5,6])